import "@/uploads/styles/privacy/privacy.css";

export default function PrivacyPolicyPage() {
  return (
    <main>
      <div className="privacy-secA sec-pad-all mt-hdrfxd">
        <div className="container">
          <div className="website-content">
            <h1>
              Privacy <span>Policy</span>
            </h1>

            <p>
              THIS PRIVACY POLICY (“PRIVACY POLICY”) SETS FORTH THE MANNER OF
              COLLECTION, USE AND DISCLOSURE OF INFORMATION GATHERED ON THE
              AFFORDPLAN WEBSITE. PLEASE READ THIS PRIVACY POLICY CAREFULLY. BY
              CONTINUING TO USE THE SERVICES, OR ACCESSING THE WEBSITE YOU AGREE
              TO THE TERMS OF THIS PRIVACY POLICY. IF YOU DO NOT AGREE TO THE
              SAME, YOU SHOULD NOT ACCESS OR USE THE WEBSITE OR AVAIL OF THE
              SERVICES.
            </p>

            <p>
              This document is an electronic record in terms of the Information
              Technology Act, 2000 and rules framed thereunder, as applicable
              and in accordance with such other applicable provisions under
              applicable laws pertaining to electronic records in various
              statutes (as amended from time to time). This document is
              published in accordance with the provisions of Rule 3(1) of the
              Information Technology (Intermediary Guidelines) Rules, 2011 which
              require the publishing of the rules and regulations, Terms of Use
              and this Privacy Policy for access or usage of the Affordplan
              Platform (as defined hereinafter) for mobile and handheld devices
              and compliance with Digital Personal Data Protection Act, 2023.
              This electronic record is generated by a computer system and does
              not require any physical or digital signatures.
            </p>

            <p>
              Affordplan is operated by ‘Usekiwi Infolabs Private Limited’, a
              company duly incorporated in India (“Company” or “Affordplan”).
              These terms of use (“Terms”) govern Your use of our website{" "}
              <a
                href="https://www.affordplan.com"
                target="_blank"
                rel="noopener noreferrer"
              >
                www.affordplan.com
              </a>{" "}
              (“Website”) and our “Affordplan Swasth” application for mobile and
              handheld devices (“Application”) including any subdomains thereof
              are jointly referred to as the “Affordplan Platform”.
            </p>

            <p>
              The following terms of the privacy policy are by and between the
              Company and the Customers/ Permitted User/ End User (“User” or
              “You” or “Your”) of the Affordplan Platform. The Company provides
              a platform through its Website and/or Application and provides
              Services.
            </p>

            <p>
              This Privacy Policy does not apply to the websites of Our
              Merchants, business partners, corporate affiliates or any other
              third parties, even if their websites are linked to the Affordplan
              Platform. We recommend You review the respective privacy
              statements of the other parties with whom You interact.
            </p>

            <p>
              By accessing the Affordplan Platform or otherwise using the
              Affordplan Platform, You expressly consent to Our collection,
              storage, use and disclosure of the User Data in accordance with
              the terms of this Privacy Policy. All information in this Privacy
              Policy applies to You unless otherwise indicated.
            </p>

            <p>
              Please note: All information in this Privacy Policy applies to You
              unless otherwise indicated. In this Policy, the term “Personal
              Data” shall mean any data of an individual/ organization/ company
              who is identifiable by or in relation to such data.
            </p>

            <p>
              Further, any and all terms not defined herein but capitalized
              shall derive the meaning from the Terms of Use or the Merchant
              Agreement or the User Agreement as the context so requires.
            </p>

            <h2>
              1. COLLECTION, STORAGE AND USE OF INFORMATION RELATED TO YOU
            </h2>

            <p>
              When the End User access or utilize the Affordplan Platform, these
              Users are required to provide certain Personal Data and
              non-personal information which may include (such information and
              correspondences hereinafter collectively referred to as “User
              Data”):
            </p>

            <ul>
              <li>
                Information about Your identity, including but not limited to,
                Your name/guest name, nationality, gender, marital status, age,
                email address, product details and particulars thereof (if any);
              </li>
              <li>KYC details including Aadhaar, Pan, etc.;</li>
              <li>
                Your financial information, such as Your banking details and any
                information relating to Your income;
              </li>
              <li>
                Your contact details such as Your physical addresses, postal
                addresses, telephone and fax numbers and the like;
              </li>
              <li>
                Your medical details such as details of disease or ailment,
                previous medical history or records etc.;
              </li>
              <li>
                Payment and Account Information: Your account history with Us
                including (without limitation) all billing information and
                communications, payment history etc.;
              </li>
              <li>
                Content, information about Your correspondents, and the
                destination/origin of communications between You and any other
                person using Our Services, which include email communications,
                blog, chat room and discussion board communications, instant
                message communications, experts forum communications, fax mail
                communications, membership of mailing lists etc. as applicable;
              </li>
              <li>
                Your usernames, passwords, email addresses and other
                security-related information used by You in relation to Our
                Services.
              </li>
            </ul>

            <p>Other information may include:</p>

            <ul>
              <li>
                Cookies and electronic tools to gather data on individual
                interests for enhanced Affordplan Platform responsiveness. This
                includes server logs with details like web requests, IP
                addresses, browser type, language, date, time, and unique
                browser identifiers primarily for user authentication;
              </li>
              <li>
                location and device information while using the Application,
                using it to provide service-related suggestions if needed;
              </li>
              <li>
                Emails and other communications sent to Us are retained to
                process inquiries, respond to requests, and enhance services.
              </li>
            </ul>

            <p>
              We may also collect payment information such as Your payment card
              number, expiration date, billing and shipping address. By using
              the Service, You consent to the recording, storage, and disclosure
              of such communications You send or receive for these purposes. We
              may also store and process prescriptions, treatment notes,
              recommendations and other data generated by Merchants on or
              through the Platform, and data shared by third parties such as
              diagnostics-related information; prescription-related information
              etc. and may retain such material for Our records for the duration
              of You availing the Services or for any such period required or
              permitted under applicable law in the form of images.
            </p>

            <p>
              We collect only the User Data that We believe to be relevant and
              is required to provide effective Services that You voluntarily
              elect to provide Us. You may, at any instance, choose not to
              provide Us the User Data, however, in such a case We may not be
              able to offer You (partially or entirely, as the case may be) the
              Services provided by Us.
            </p>

            <p>
              Additionally, We collect Your User Data in order to record,
              support and facilitate the provision of Services to You,
              including, via third parties whom You agree to engage with through
              the use of the Affordplan Platform, to assist You with insurance
              services, customer services, technical support issues, to follow
              up with You, to otherwise support Your relationship with Us and/or
              to prevent fraud and unlawful activities.
            </p>

            <p>
              Please note: To make it easier to manage Your buying, You can open
              a User Account. This allows You to save Your personal settings;
              review previous plans availed and manage future planning. When You
              visit Our Affordplan Platform, even if You do not make a purchase,
              We may collect certain information, such as data that identifies
              Your computer/mobile device, device-specific settings and
              characteristics and latitude/longitude details etc.
            </p>

            <h2>2. PURPOSE OF USERS DATA</h2>

            <ul>
              <li>
                We use Your Data to complete and administer Your online
                transactions through the Affordplan Platform.
              </li>
              <li>
                We offer the User Account facility on Our Affordplan Platform.
                We use the information You give Us to administer this, allowing
                You to manage Your Transactions, take advantage of special
                offers, make future Transactions more easily and manage Your
                personal settings.
              </li>
              <li>
                Managing personal settings allows You to see Transactions that
                You have undertaken using the Affordplan Platform before.
              </li>
              <li>
                When You undertake Transactions using the Affordplan Platform or
                set up the User Account, We may use Your contact information to
                send You news about similar offers and plans.
              </li>
              <li>
                We may also send to the Users regular newsletters by email. You
                can opt- out, or unsubscribe, from marketing communication at
                any time.
              </li>
              <li>
                Based on the information You share with Us, individualized
                offers may be shown to You on the Affordplan Platform, in mobile
                apps or on third-party applications, including social media
                websites.
              </li>
              <li>
                We may use the User’s Data for the detection and prevention of
                fraud and other illegal or unwanted activities or disclose the
                User’s Data if required as per applicable laws.
              </li>
              <li>
                The Affordplan Platform collects personal information such as
                name, phone number, address, and age, as well as, on occasions,
                including government ID as per healthcare and tax laws and
                regulations in the country for authentication of user/consumer
                and verification of authentic payment.
              </li>
            </ul>

            <h2>3. LINKS TO THIRD-PARTY WEBSITES AND ADVERTISING</h2>

            <p>
              We may use third-party service providers to process the End User’s
              Data on Our behalf for the purposes specified above. To further
              elaborate in this regard, We may instruct third parties to contact
              You.
            </p>

            <p>
              We also work with third-party payment service providers to
              facilitate payment or payment guarantees. We also work with
              third-party advertisement networks to market Our services on other
              platforms or involve third-party providers for analytical
              purposes.
            </p>

            <p>
              These third parties involved in any of these services will, as far
              as may be feasible, be bound by confidentiality agreements and
              will not be allowed to use the End User’s Data for any purposes
              other than those specified herein.
            </p>

            <p>
              We may share information with Our business partner, for example,
              as part of the administration of Your account, in order to manage
              Your plan, so that they can address queries related to Your
              transaction and for marketing purposes. In this context, Your
              information is governed by the privacy policies of the respective
              business partners.
            </p>

            <h2>4. END USER’S DATA SECURITY SAFEGUARDS</h2>

            <p>
              We use reasonable security measures to protect information from
              unauthorized access, maintain data accuracy and help ensure the
              appropriate use/disclosure of information.
            </p>

            <p>
              We host the Website in a secure server environment that uses
              firewalls and other advanced technology to prevent interference or
              access from outside intruders.
            </p>

            <p>
              We have implemented meticulous technical, organizational, and
              security protocols to avert the inadvertent loss, misuse, or
              unauthorized access, alteration, or disclosure of Your Personal
              Data.
            </p>

            <p>
              Furthermore, access to Your Personal Data is restricted to
              individuals such as employees, agents, contractors, and selected
              third parties, only when essential for legitimate business
              purposes and on a need-to-know basis.
            </p>

            <p>
              These authorized entities will exclusively process Your Personal
              Data based on Our explicit instructions and are strictly bound by
              rules of confidentiality.
            </p>

            <p>
              Additionally, We have established comprehensive procedures to
              address any suspected data security breaches. In situations where
              legal obligations dictate, We commit to promptly notifying You and
              relevant regulatory bodies of any suspected breaches.
            </p>

            <h2>5. LOYALTY PROGRAM</h2>

            <p>
              The End Users authorize the Company to collect, process,
              facilitate and remit payment collected electronically or through
              cash on pick-up for the facilitation of transactions between
              Merchant and the End User.
            </p>

            <p>
              The End User expressly agrees and opts in for the Company to send
              any promotional and transactional messages by phone, email other
              means (even if listed in the TRAI’s DND list).
            </p>

            <h2>6. DATA RETENTION</h2>

            <p>
              We keep Your Personal Data and other information to enable Your
              continued use of the Affordplan Platform, for as long as it is
              required to fulfil the relevant purposes described in this Privacy
              Policy, like an ongoing contractual relationship or accounting
              needs, or when there is a legal storage need.
            </p>

            <p>
              Data will be retained by the Company as suggested hereinabove,
              however, no claim shall be made by You or any stakeholder for the
              destruction of the Personal Data and other information.
            </p>

            <h2>7. NOTICE</h2>

            <p>
              Every request made to the User for consent with regard to the
              processing of the Personal Data shall be accompanied or preceded
              by a notice given by the Company to the User, informing the User
              of the Personal Data and the purpose for which the Personal Data
              is proposed to be processed.
            </p>

            <p>
              Further, the notice shall include the right to withdraw and the
              right to seek grievance redressal by the User.
            </p>

            <p>
              The notice shall also include the manner in which the User may
              make a complaint to the Data Protection Board as may be prescribed
              under the provisions of law time being in force.
            </p>

            <h2>8. CHANGES TO THIS PRIVACY POLICY</h2>

            <p>
              As We update, improve and expand the Affordplan Platform, we may
              change this Privacy Policy from time to time, so please refer back
              to it periodically as You will be deemed to be governed by the
              terms of such modified Privacy Policy, as it comes into effect
              from time to time.
            </p>

            <h2>9. DISCLAIMER</h2>

            <p>
              The Company does not store any account-related information or any
              credit/debit card details.
            </p>

            <p>
              The Company shall not be liable for any loss or damage sustained
              by Users as a result of any disclosure (inadvertent or otherwise)
              of any information concerning the User's account, credit cards or
              debit cards in the course of any online transactions or payments
              made for any products and/or services offered through the
              Affordplan Platform.
            </p>

            <p>
              In case any Personal Data is shared by You with the Company, which
              is not requested by the Company during registration, (whether
              mandatorily or optionally), the Company will not be liable for any
              information security breach or disclosure in relation to such
              information.
            </p>

            <p>
              In no event will any delay, failure or omission (in whole or in
              part) in enforcing, exercising or pursuing any right, power,
              privilege, claim or remedy conferred by or arising under this
              Privacy Policy or by law, be deemed to be or construed as a waiver
              of that or any other right.
            </p>

            <h2>10. CONTACT US</h2>

            <p>
              If You have any questions, concerns, or requests regarding this
              Privacy Policy or Our data practices, please contact Us at{" "}
              <a href="mailto:info@affordplan.com">info@affordplan.com</a>{" "}
              or <a href="tel:+919250050501">+91-92500 50501</a>.
            </p>

            <p>Thank You for using the Website!</p>
          </div>
        </div>
      </div>
    </main>
  );
}
