import { Suspense } from "react";
import type { Metadata } from "next";
import "./global.css";
import NextTopLoader from "nextjs-toploader";
import { Toaster } from "react-hot-toast";
import { Poppins } from "next/font/google";
import Loader from "@/app/loading";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-poppins",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${poppins.variable}`} suppressHydrationWarning>
      <body cz-shortcut-listen="true" suppressHydrationWarning>
        <NextTopLoader showSpinner={false} />
        <Suspense fallback={<Loader />}>
          {children}
        </Suspense>
        <Toaster
          position="top-center"
          reverseOrder={true}
          toastOptions={{
            duration: 1200,
            style: {
              background: "rgba(0,0,0,0.85)",
              color: "#fff",
              padding: "8px 12px",
              borderRadius: "4px",
              fontSize: "14px",
              boxShadow: "0 4px 12px rgba(0,0,0,0.15)",
              backdropFilter: "blur(6px)",
            },
            success: {
              style: {
                background: "rgba(34, 197, 94, 0.9)",
                borderRadius: "4px",
              },
              iconTheme: {
                primary: "#fff",
                secondary: "#15803d",
              },
            },
            error: {
              style: {
                background: "rgba(239, 68, 68, 0.9)",
                borderRadius: "4px",
              },
              iconTheme: {
                primary: "#fff",
                secondary: "#b91c1c",
              },
            },
          }}
        />
      </body>
    </html>
  );
}
