import "@/uploads/styles/privacy/privacy.css";

export default function TermsConditionsPage() {
  return (
    <main>
      <div className="privacy-secA sec-pad-all mt-hdrfxd">
        <div className="container">
          <div className="website-content">
            <h1>
              Terms <span>of Use</span>
            </h1>

            <p>
              PLEASE READ THESE TERMS AND CONDITIONS OF USE CAREFULLY. BY ACCESSING THIS WEBSITE AND ANY PAGES THEREOF, YOU AGREE TO BE BOUND BY THE TERMS AND CONDITIONS OF USE BELOW AND/OR ANY SUCH TERMS AND CONDITIONS OF USE AS ARE COMMUNICATED ON THE PAGES THEREOF. IF YOU DO NOT AGREE TO THE TERMS AND CONDITIONS OF USE BELOW AND/OR ANY SUCH TERMS AND CONDITIONS OF USE AS ARE COMMUNICATED ON THE PAGES THEREOF, DO NOT ACCESS THIS WEBSITE, OR ANY PAGES THEREOF. USERS ARE CAUTIONED AGAINST RESPONDING TO CALLS OR EMAILS SOLICITING PAYMENT FROM WEBSITES CLAIMING TO OFFER SIMILAR SERVICES UNDER THE NAME OUR COMPANY.
            </p>

            <p>
              This document is an electronic record in terms of the Information Technology Act, 2000 and rules framed thereunder, as applicable and in accordance with such other applicable provisions under applicable laws pertaining to electronic records in various statutes (as amended from time to time).
            </p>

            <p>
              This document is published in accordance with the provisions of Rule 3(1) of the Information Technology (Intermediary Guidelines) Rules, 2011 which require the publishing of the rules and regulations, Privacy Policy (as defined hereinbelow) and Terms (as defined hereinbelow) for access or usage of the Website (as defined hereinbelow) and Application (as defined hereinbelow) for mobile and handheld devices and compliance with Digital Personal Data Protection Act, 2023. This electronic record is generated by a computer system and does not require any physical or digital signatures.
            </p>
            <p>
              Affordplan is operated by 'Usekiwi Infolabs Private Limited', a company duly incorporated in India ("Company" or "Affordplan"). These terms of use ("Terms") govern Your use of our website{" "}
              <a href="https://www.affordplan.com" target="_blank" rel="noopener noreferrer">
                www.affordplan.com
              </a>{" "}
              ("Website") and our "Affordplan Swasth" application for mobile and handheld devices ("Application") including any subdomains thereof are jointly referred to as the "Affordplan Platform".  By agreeing to these Terms, You also agree to our other policies; including but not limited to privacy policy ("Privacy Policy"), as displayed on the Website and amended from time to time. The terms capitalised herein are defined in the Glossary hereto and any such terms not defined shall derive their meaning from the User Agreement or the Merchant Agreement as the case may be.
            </p>
            <p>
              These Terms pertain to the User's (as defined hereinbelow) engagement with Affordplan Platform and the User's utilization of Affordplan Platform's Services. The terms "you", "your" and "yours" hereinafter referred to shall include the Users (both Permitted User and End User) and individually as Permitted User and End User. Further, the terms "We", "Us", and "Our" shall mean the Company and/or its affiliates.
            </p>

            <h2>1. ACCESSING THE PLATFORM</h2>
            <p>
              Affordplan Platform provides Services to the the Users through the Affordplan App.
            </p>
            <p>
              Affordplan Platform, along with its associated products, Services, or subscribed-to items (whether or not remunerated by the User), is expressly intended for the exclusive utilization of the Users.
            </p>
            <p>
              We will from time to time make available the Affordplan Platform updates to improve performance, fix bugs or errors, enhance functionality, reflect changes to the operating system or address security issues. We recommend that you install these updates, and in case of major updates, the Affordplan Platform and/or the Services may not function unless you install these major updates.
            </p>

            <h2>2. REGISTRATION AND ACCEPTANCE</h2>
            <h3>Account creation of the End User</h3>
            <p>
              You will be required to register on the Affordplan Platform to utilise the Services and share Your details to access the Affordplan Platform by registering on the Affordplan Platform. You agree to share the required details in order to create an account with the Affordplan Platform. Further, the End User shall indicate a User name for the account and an associated password (hereinafter referred to as 'End User Account').
            </p>
            <p>
              The End User shall be required to confirm that they have read and abide by these Terms and the User Agreement as displayed on the Affordplan Platform before the completion of signing up for the End User Account.
            </p>
            <p>
              The End User shall pay a one-time non-refundable registration fee at the time of registration (unless otherwise offered by the Company). The registration fees shall be valid for a period of 1 (one) year from the date of activation. Upon expiry of the 1 (one) year validity period, the Company may charge renewal fees from the End Users for continued access to the AffordPlan App and its Services. The renewal fees applicable shall be notified to the Users before the expiry of the validity period. Non-payment of renewal fees may result in suspension or termination of the User's account and access to the App as per the Company's policies and including immediate expiry of Swasth Points.
            </p>
            <p>
              The End User shall be responsible for maintaining the confidentiality of the username and password. Additionally, the End User shall be responsible for all activities associated with the End User Account.
            </p>
            <p>
              The End User hereby acknowledges that one account (one mobile no. and email id) can be used for making payments to one Merchant through Affordplan Platform and for payments to be made to any other Merchant shall be done through a different account (different mobile no. and email id).
            </p>
            <p>
              The End User hereby acknowledges that the account will be activated only upon receipt of required details by the Company and any additional details as may be required from time to time, and the Company may at its sole discretion reject the activation of the account.
            </p>
            <p>
              The End User agrees that the Company shall not be liable for the activities or consequences of the use or misuse of any information in the End User Account in cases, including, where the End User shared the login details with any third person or has failed to update the mobile phone number and/or e-mail address on the Affordplan Platform.
            </p>

            <h3>Account creation of the Permitted User</h3>
            <p>
              The Permitted User will be provided with unique login credentials (hereinafter referred to as 'Permitted User Account'), which can be accessed by its employees, staff or representatives only upon execution of the Merchant Agreement.
            </p>
            <p>
              The Permitted User shall be responsible for maintaining the confidentiality of the username and password. Additionally, the Permitted User shall be responsible for all activities associated with the Permitted User Account.
            </p>
            <p>
              For the purposes of this section, the Permitted User shall be responsible for the acts of its employees, staff or representatives and shall indemnify the Company.
            </p>

            <h2>3. ACCESS TO DASHBOARD FOR THE END USER</h2>
            <p>
              After the End User has registered on the Affordplan Platform, the Company will provide with the access to Affordplan Platform and the dashboard. With access to the dashboard, the End User will be able to view the Services that the Company provides and make payments for the Healthcare Services to be obtained from the Merchant and avail other Services of the Service Providers as displayed on the Affordplan App.
            </p>
            <p>
              The Dashboard will be accessible through the Login ID and Password. The End User having access to the Login ID and Password will be able to manage and control the Services. In such a case, the End User shall ensure that the access to the Login ID and Password to the dashboard shall remain with him/ her and not be passed on to any third person.
            </p>
            <p>
              We shall make the Services available through the dashboard once we have received all the required documents and the End User has accepted these Terms and the terms and conditions stipulated in the User Agreement for availing the Services of the Company.
            </p>

            <h2>4. PAYMENT OBLIGATIONS OF THE END USER</h2>
            <p>
              While availing any of the Payment Options available on the Affordplan Platform, we will not be responsible or assume any liability, whatsoever in respect of any loss or damage arising directly or indirectly to the End User due to any of the following:
            </p>
            <ul>
              <li>Lack of authorisation for any Transaction/s; or</li>
              <li>Exceeding the preset limit mutually agreed by the End User and "Bank/s"; or</li>
              <li>Any payment issues arising out of the Transaction; or</li>
              <li>Decline of Transaction for any other reason/s; or</li>
              <li>RBI and banking regulations applicable to the End User including but not limited to KYC compliance.</li>
            </ul>
            <p>
              Affordplan Platform offers an integrated payment platform that offers a secure and user- friendly process to facilitate Transactions for availing Healthcare Services and other Services of the Company.
            </p>
            <p>
              All payments made towards the Services through the Affordplan Platform shall be compulsorily in Indian Rupees acceptable in the Republic of India. Affordplan Platform will not facilitate Transactions with respect to any other form of currency with respect to the purchases made on Affordplan Platform.
            </p>
            <p>
              Any payment if withheld and not transferred to the Permitted User for any reason whatsoever, the same shall be dealt with by the Company in accordance with the refund policy of the payment platforms and as may be communicated to the End User.
            </p>
            <p><strong>Please note that:</strong></p>
            <p>
              Use of the Services of the Company shall not render the Company liable or responsible for the non-delivery, non-receipt, non-payment, damage, breach of representations and warranties or non-performance of Healthcare Services or fraud with respect to Healthcare Services provided by the Merchants.
            </p>
            <p>
              You have specifically authorized the Affordplan Platform or its Service Providers to collect, process, facilitate and remit payments and/or the Transactions electronically to and from other Users in respect of Transactions through the Payment Options. The End User relationship with the Company is on a principal-to-principal basis and by accepting these Terms, the End User agrees that the Company is an independent contractor for all purposes.
            </p>
            <p>
              The End User understands, accepts and agrees that the Payment Optionsprovided by the Affordplan Platform shall not mean banking or financial service but a facilitation or accessibility provider to avail the Services of the Company, the Healthcare Services of the Merchants or the services of the Service Providers.
            </p>

            <h2>5. SWASTH POINTS</h2>
            <p>
              The Swasth Points on each Transaction will be based on the terms and conditions of the Merchants, in accordance to its own policies and as displayed on the Affordplan Platform. In case the prices are higher or lower on the date of execution, any additional charges will be collected or refunded as the case may be, at the time of the execution of Services by the Merchants.
            </p>
            <p>
              The Contract is brought into existence between (i) Merchants and the Customers and (ii) Merchants and the Company. The Company, as a facilitator, interacts with the Customer with authority to perform the agreed duties entrusted. Services are provided by the Merchants to the Customer. All monies collected by the Company belong to the Merchants. The Company is entitled to the fee for the Services, and the received amount is remitted after adjusting for such monies as may be agreed in terms of the Merchant Agreement
            </p>
            <p>
              Swasth Points are virtual points earned by the End Users for payments made in pursuance of availing the Healthcare Services from the Merchant and making the payments through the AffordPlan App or in accordance with the terms of this Agreement.
            </p>
            <p>
              The number of Swasth Points awarded per Transaction may vary depending on the Merchant and the specific Healthcare Services availed during such Transactions.
            </p>
            <p>
              Swasth Points can be redeemed on future Healthcare Services at such facility operating under the same brand name, if allowed by the respective Merchant as appearing on the AffordPlan App.
            </p>
            <p>
              Swasth Points shall have a fixed validity (which shall be communicated by the Merchant while onboarding the End User) from the last usage date of such Swasth Points, post which the Swasth Points shall lapse, unless the Merchant and the Company mutually decide to extend the validity of such Swasth Points.
            </p>
            <p>
              Where the Merchant or the Company ceases its operations or where the arrangement between the Merchant and the Company is terminated the Merchant or the Company shall refund the amount of the Swasth Points to the respective End User in such form as may be decided by the Company at the time of refund, which may be subject to applicable charges at the discretion of the Merchant or the Company. The responsibility of refund shall be of the Merchant or the Company as may be agreed upon between the Merchant and the Company in terms of the Merchant Agreement.
            </p>
            <p>
              Every effort will be made (but not as an obligation) by the Company for all contracts to be co-terminus so as to facilitate the optimization of balance in the account of the End User.
            </p>

            <h2>6. FRAUDULENT TRANSACTIONS</h2>
            <p>
              The Users shall not engage in any form of fraudulent transactions or criminal offences. Any fraudulent schemes or activities aimed at defrauding the Customers or the Merchant or the Service Providers while using the Affordplan Platform shall be reported under the relevant law to the appropriate authorities. The Company reserves the right to withdraw its Services in such cases.
            </p>
            <p>
              In the event that the Company is notified of an unauthorized debit reported by the End User, the Company shall be entitled to suspend settlement of the amount associated with the fraudulent transaction pending inquiries, investigations, and resolution by the payment gateway. If the fraudulent transaction results in a chargeback, it shall be resolved by the Affordplan Platform only upon verification from the payment gateways.
            </p>
            <p>
              Furthermore, the Company reserves the right to close, suspend, limit, or put on hold a User's access to their account and/or the funds available therein in the following scenarios:
            </p>
            <ul>
              <li>If the End User's KYC credentials are found to be ingenuine or fake.</li>
              <li>For violation of any provisions of these Terms or the Merchant Agreement or the User Agreement.</li>
              <li>For violation of any provisions of any other agreement that the User has entered into or might enter into with the Company.</li>
              <li>For violation of any applicable laws.</li>
            </ul>
            <p>
              The right to close, suspend, limit, or put on hold on the End User's access account with the Company shall remain with the Company, in accordance with the extant rules, regulations, or guidelines regarding KYC, as well as to the satisfaction of the Company, without prejudice to any other legal remedy that the Company is entitled to pursue under applicable law.
            </p>
            <p>
              The Company reserves the right to settle the amounts in excess from the Users, if under any Transaction the Company is paid less than as agreed.
            </p>

            <h2>7. RESPONSIBILITIES OF THE USERS</h2>
            <h3>Responsibilities of the End User</h3>
            <ul>
              <li>The End User shall have attained the age of 18 (Eighteen) years.</li>
              <li>The End User shall be capable of entering into a lawful contract and to be bound by these Terms.</li>
              <li>The End User shall comply with all applicable laws and regulations.</li>
              <li>The End User agrees that any liability in relation to any Healthcare Services availed from the Merchants shall solely be dealt with by the Merchants and any End User shall not have any claim whatsoever pertaining to these Healthcare Services against the Company.</li>
            </ul>

            <h3>Responsibilities of the Permitted User</h3>
            <ul>
              <li>The Permitted User accepts these Terms on behalf of a Merchant.</li>
              <li>The Permitted User shall comply with all applicable laws and regulations.</li>
              <li>The Permitted Users shall be responsible for the Healthcare Services being offered or obtained, as the case may be and under any circumstances shall not hold the Company responsible for any deficiency, mistake or error. The Company's responsibility shall be limited to the Services being provided to the Permitted Users.</li>
              <li>The Permitted User agrees to abide by the provisions of the applicable laws while providing these Healthcare Services and shall indemnify the Company for any third- party claims.</li>
            </ul>

            <h3>Responsibilities of the Users</h3>
            <p>
              No User undertakes any unauthorized reproduction, download, recreation, sharing of passwords, sublicensing, or any form of distribution not in compliance with these Terms, if undertaken shall be treated as a misuse of the Affordplan Platform or the Services. The Company retains the right to take appropriate actions to safeguard against loss of revenue, damage to reputation, or claims for damages. Such actions may include suspending Your Service or access, as well as reporting the matter to relevant authorities. In the event You are found to be copying, misusing, transmitting or crawling any data, photographs, graphics or any information available on the Affordplan Platform for any purpose other than that being a bona fide purpose, the Company reserves the right to take such action that it deems fit including stopping access, suspending the account and claiming damages.
            </p>
            <p>
              By utilizing the Affordplan Platform, You expressly authorise the Company to utilise information pertaining to Your actions on the Affordplan Platform for the purpose of displaying advertisements, offers, and other content, sponsored or otherwise, across our Services. This authorization is conferred without any requirement for compensation to You. The data and information concerning You are utilized to deliver relevant suggestions and recommendations to You and other Users.
            </p>
            <p>
              The User to the Affordplan Platform and/or its affiliated websites does hereby specifically agree that it shall, at all times, comply with the requirements of the Information Technology Act, 2000 and Digital Personal Data Protection Act, 2023 as also the rules, regulations, guidelines, bye laws and notifications made thereunder while assessing or feeding information or data into the computers, computer systems or computer network of the Affordplan Platform. The said User of the Affordplan Platform and/or its affiliated websites does further unequivocally declare that in case it violates any provisions of the said acts and/or rules, regulations, guidelines, bye laws and notifications made thereunder, it shall be solely responsible for all his acts, deeds and things and that he alone shall be liable for civil and criminal liability thereunder or under any other law for the time being in force.
            </p>

            <h2>8. USAGE CONDUCT</h2>
            <h3>Conduct by the End User</h3>
            <p>
              You are under an obligation to use this Affordplan Platform for reasonable and lawful purposes only and shall not indulge in any activity that is not envisaged through the Affordplan Platform. You shall use this Affordplan Platform, or the Services or any other services availed through it, for personal, non-commercial use only and shall not re-sell the same to any other person.
            </p>
            <p>
              The Company shall not be liable for any failure or default to provide access to the Affordplan Platform on account of any failure or delay by You to register with the Affordplan Platform for such access.
            </p>
            <p>
              Any configuration or set-up of the Devices for access to the Affordplan Platform shall be the sole responsibility of the User.
            </p>
            <p>
              The Company shall collect, store, process and use the User information in accordance with the Company's Privacy Policy. The use of the Affordplan Platform and submission of Personal Data shall be construed as the User giving consent for the collection and use of information disclosed by the User to the Company, in accordance with the Privacy Policy.
            </p>
            <p>
              The User shall not knowingly include or use any false or inaccurate information in the personal information.
            </p>
            <p>
              The User shall not take any action that interferes with, degrades or adversely affects the Company and/or the Affordplan Platform.
            </p>

            <h3>Conduct by the Users</h3>
            <p>
              User shall only access the Affordplan Platform using authorised and lawful means.
            </p>
            <p>
              The User shall not use the Affordplan Platform, or any portion thereof, to transmit, publish, post, upload, distribute or disseminate any inappropriate, harassing, abusive, defamatory, libellous, obscene, illegal or deceptive content.
            </p>
            <p>
              The User shall not use the Affordplan Platform in a manner that (a) is prohibited by any law or regulation, or facilitates the violation of any law or regulation, or (b) will disrupt a third party's similar use, or (c) violate or temper with the security of the Affordplan Platform.
            </p>
            <p>
              The User shall ensure that the Affordplan Platform is not used to upload, post, transmit, or otherwise make available any content that contains a virus or any other form of malicious code or data that is likely or intended to have an adverse impact on or provide unauthorized access to, the Affordplan Platform or any other software, hardware, services or data.
            </p>
            <p>
              The User shall not attempt to gain unauthorised access to any accounts, computer systems or networks connected to the Affordplan Platform, through hacking, or any other means, or obtain or attempt to obtain any materials or information through any means not intentionally made available to the User.
            </p>
            <p>
              The User shall not copy, modify, adapt, translate, or reverse engineer any portion of the Affordplan Platform, its content or materials and/or the services. Further, the User shall not use the Affordplan Platform to develop or to assist anyone in developing a competitive business, service or for other competitive purposes.
            </p>
            <p>
              The User acknowledges that from time to time, the Company may apply Upgrades to the Affordplan Platform, and that such Upgrades may result in changes to the appearance and/or functionality of the Affordplan Platform. The User may be required to install certain Upgrades or updates to the software in order to continue to access or use the Affordplan Platform or portions thereof.
            </p>
            <p>
              Without explicit and written consent from the Company, You agree not to reproduce, publish, distribute, or otherwise use any data collected on this Affordplan Platform for commercial or non-commercial purposes. This includes but is not limited to, personal information, User-generated content, and any other data accessible on the Affordplan Platform. Any unauthorized reproduction or publication of such data is strictly prohibited and may result in legal action.
            </p>

            <h2>9. RIGHTS OF THE COMPANY</h2>
            <p>The Company may at its sole discretion:</p>
            <ul>
              <li>Exercise the authority to curtail, temporarily suspend, or permanently terminate User's access to.</li>
              <li>Exercise discretion in declining, relocating, or deleting any content that a User may choose to submit.</li>
              <li>Perform the action of relocating or deleting any content accessible on the Affordplan Platform.</li>
              <li>Institute comprehensive principles and boundaries governing the utilization of the Affordplan Platform and the Services.</li>
              <li>Assign its rights and liabilities to all User accounts hereunder to any entity. Further post the assignment, intimation of such assignment shall be sent to all User's registered email ID.</li>
            </ul>
            <p>
              Users hereby grant their consent to receive various forms of communication, including announcements, administrative notifications, and promotional materials from the Company or any entities affiliated with the Company, including its partners and licensors.
            </p>
            <p>
              The Company retains the right to take appropriate actions against the Users, including but not limited to safeguarding against loss of revenue or reputation, seeking damages, terminating Services or access, and reporting such instances to relevant authorities. In the event of any unauthorized copying, misuse, transmission, or crawling of data, photographs, graphics, or information from the Affordplan Platform for purposes other than bona fide intentions, the Company reserves the right to undertake suitable measures, including cessation of access and pursuit of damages.
            </p>

            <h2>10. DISCLAIMER OF WARRANTIES AND LIABILITIES</h2>
            <p>
              This Affordplan Platform, all the materials and payment plans (including but not limited to Transaction or Services) included on or otherwise made available to You through this Affordplan Platform are provided on an "as is" and "as available" basis without any representation or warranties, express or implied except otherwise specified in writing.
            </p>
            <p>No representations, warranties or guarantees whatsoever are made by the Company as to the following—</p>
            <ul>
              <li>accuracy, adequacy, reliability, completeness, suitability or applicability of the information to a particular situation;</li>
              <li>the quality of any Services, content, information, or other material on the Affordplan Platform will meet the User's expectations or requirements;</li>
              <li>any errors in the Affordplan Platform will be corrected; or</li>
              <li>other warranties relating to performance, non-performance, or other acts or omissions of the Company, its officers, directors, employees, affiliates, agents, licensors, or suppliers.</li>
            </ul>
            <p>
              The Company does not warrant that the Affordplan Platform; information, content, materials, Transaction or Services included on or otherwise made available to You through the Affordplan Platform; the servers; or electronic communication sent from us are free of viruses or other harmful components, despite our best efforts to prevent these incidents.
            </p>
            <p>
              Nothing on the Affordplan Platform constitutes or is meant to constitute, advice of any kind. All the information available on the Affordplan Platform is governed by different laws and policies of the respective Merchants, if the Merchant is unable to deliver required Services due to implications of different laws or/and its own policies, Merchants shall be liable to refund the amount received in advance from the User for the Services that could not be provided to such User by the Merchants.
            </p>
            <p>
              In no event will any delay, failure or omission (in whole or in part) in enforcing, exercising or pursuing any right, power, privilege, claim or remedy conferred by or arising under the Privacy Policy or by law, be deemed to be or construed as a waiver of that or any other right, so as to bar the enforcement of that, or any other right, power privilege, claim or remedy, in any other instance at any time or times subsequently.
            </p>
            <p>
              Notwithstanding anything contained elsewhere in these Terms, in no event shall the Company be liable to the User for any costs or loss incurred or suffered by the User or anyone claiming under the User, including but not limited to any special, exemplary, consequential, incidental, punitive or indirect damages on any theory of liability, whether in contract, tort (including without limitation negligence), strict liability or otherwise. In no event or circumstance shall the Company be under any liability to make good any loss whether by way of any monetary payment or otherwise.
            </p>

            <h2>11. LINKS TO THIRD-PARTY APPLICATIONS, SERVICES AND PRODUCTS</h2>
            <p>
              Within the Affordplan Platform, the User may encounter links to other websites or applications that are independently owned and managed by third parties. The User's interaction with these external sites is subject to the terms and conditions, if any, stipulated by those specific websites or applications. The Company does not exercise control over any websites or applications outside of its own Affordplan Platform and therefore disclaims responsibility for the content found on any third-party websites or applications. It is crucial to understand that the Company's inclusion of third-party content or links to third-party websites and applications should not be interpreted as an endorsement or validation of such third-party websites or applications by the Company.
            </p>
            <p>
              Users' correspondence, Transactions/offers or related activities with third parties, including payment processors, are solely between the User and that third party. User's correspondence, Transactions and usage of the services/offers of such third party shall be subject to the terms and conditions, policies and other service terms adopted/implemented by such third party, and the User shall be solely responsible for reviewing the same prior to transacting or availing of the services/offers of such third party. User agrees that the Company shall not be responsible or liable for any loss or damage of any sort incurred as a result of any such Transactions/offers with third parties. Any questions, complaints, or claims related to any third-party product or service should be directed to the appropriate vendor.
            </p>
            <p>
              The Affordplan Platform amalgamates content that is both originated by the Company and provided by third parties. Notably, the Company does not furnish any warranties concerning the precision, entirety, or quality of content contributed by third parties. Therefore, Users are explicitly advised against placing unwarranted reliance on third- party content when availing themselves of the Company services made available on the Affordplan Platform.
            </p>

            <h2>12. INTELLECTUAL PROPERTY RIGHTS</h2>
            <p>
              The User acknowledges that any and all Intellectual Property Rights (including but not limited to all the content of the Affordplan Platform, trademark, copyright, patent, service marks, etc.) and other proprietary rights in relation to the Affordplan Platform including without limitation any derivatives, improvements or modifications which ownership is directly attributable to the Company (expressly excluding any personal information, intellectual property which belongs to a third party) and any suggestions, ideas, enhancement requests, feedback, recommendations or other information provided by the User or any other party relating to the Affordplan Platform or the Services shall vest completely and fully with the Company within and beyond the territory of India and the User shall have no right or claim to such intellectual property in any manner whatsoever.
            </p>
            <p>
              The Affordplan Platform amalgamates content generated by the Company, its partners, affiliates, licensors, associates, and Users. The intellectual property rights, ('Intellectual Property Rights'), governing all foundational software underpinning the Affordplan Platform and the material presented within it, inclusive of, though not limited to, software, advertisements, written content, photographs, graphics, images, illustrations, trademarks, logos, audio or video clips, and animations, are the exclusive property of the Company, its partners, licensors, and associates. Users are expressly prohibited from modifying, publishing, transmitting, participating in the transfer or sale of, reproducing, crafting derivative works from, distributing, publicly performing, publicly displaying, or in any manner exploiting any materials or content featured on the Affordplan Platform, be it in its entirety or in part, without obtaining prior written authorization from the Company.
            </p>
            <p>
              Users shall bear exclusive responsibility for all content, whether publicly disseminated or privately transmitted, that they upload, post, send via email, transmit, or otherwise share on the Affordplan Platform ("Users' Content"). Each User affirms and guarantees that they possess full ownership of all Intellectual Property Rights associated with their Users' Content and assure that no aspect of their Users' Content infringes upon the rights of any third party. Furthermore, Users pledge not to showcase or employ the names, logos, marks, labels, trademarks, copyrights, or other intellectual and proprietary rights belonging to third parties on the Affordplan Platform. Users consent to indemnify and safeguard the Company, along with its directors, personnel, affiliates, and assignees, against any and all expenses, damages, losses, and liabilities, including legal costs and attorney fees, arising from any third-party claims, particularly those related to the violation of Intellectual Property Rights due to the display or utilization of names, logos, marks, labels, trademarks, copyrights, or other intellectual and proprietary rights on the Affordplan Platform, whether by the User directly or through their actions or inactions.
            </p>
            <p>
              The names, logos, marks, labels, trademarks, copyrights, and intellectual and proprietary rights displayed on the Affordplan Platform and owned by any individual (including Users), organization, or third party are unequivocally acknowledged as the exclusive property of their respective owners. Any disputes, controversies, or matters arising concerning these names, logos, marks, labels, trademarks, copyrights, or intellectual and proprietary rights should be promptly and directly directed to the respective rights holders, with notice to the Company.
            </p>
            <p>
              We respect the intellectual property of others. If You believe that Your Intellectual Property Rights have been used in a way that gives rise to concerns of infringement, contact the Grievance Officer (details under Clause 25 of these Terms).
            </p>

            <h2>13. PRIVACY POLICY</h2>
            <p>
              All information collected from Users, including but not limited to personal information, anonymised data and payment information, if any, is subject to the Company's Privacy Policy which is available at{" "}
              <a href="https://www.affordplan.com/privacy-policy" target="_blank" rel="noopener noreferrer">
                https://www.affordplan.com/privacy-policy
              </a>.
            </p>
            <h2>14. FEEDBACK</h2>
            <p>
              As a participant, the User agrees to use careful, prudent, and good judgment when leaving feedback for other Users of the Affordplan Platform. In the event the feedback violates these Terms, is inappropriate or violates the propriety or privacy of another User, the Company, in its sole discretion, may delete the User's feedback or any User postings; and/or report to law enforcement authorities any actions that may be illegal, and any reports it receives of such conduct. As mandated by the law or at the Company's sole discretion, the Company shall cooperate with law enforcement agencies in any investigation of alleged illegal activity on the Affordplan Platform.
            </p>
            <p>
              <strong>Reporting inappropriate use of feedback:</strong> The User may contact the Company regarding any inappropriate use of feedback via email at{" "}
              <a href="mailto:swasth@affordplan.com">swasth@affordplan.com</a>.
            </p>
            <p>
              The Company does not and cannot review every posting or listed Healthcare Services made on the Affordplan Platform. These Terms do not require the Company to monitor, police or remove any postings or other information submitted by the User or any other User and the Company shall not be responsible for any ensuing liability.
            </p>

            <h2>15. CANCELLATION / INACTIVATION / DELETION</h2>
            <p>
              You may request for deletion of your account by reaching us at{" "}
              <a href="tel:+919250050501">+91 9250050501</a> or writing to us at{" "}
              <a href="mailto:swasth@affordplan.com">swasth@affordplan.com</a>. Please note that, Affordplan retains Data for as long as necessary for the use of our products and/or services or to provide access to and use of our website or mobile application, or for other essential purposes such as complying with our legal obligations, resolving disputes, enforcing our agreements and as long as processing and retaining your Data is necessary and is permitted by applicable law. Because these needs can vary for different data types and purposes, actual retention periods can vary significantly.
            </p>
            <p>
              Even if we delete your Data, including on account of exercise of your right under this clause it may persist on backup or archival media for audit, legal, tax or regulatory purposes. If any court or competent authority finds that any provision of this Privacy Notice (or part of any provision) is invalid, illegal or unenforceable, that provision or part-provision will, to the extent required, be deemed to be deleted, and the validity and enforceability of the other provisions of this Privacy Notice will not be affected.
            </p>
            <p>
              Use of the App is available only to persons who can form a legally binding contract under the Indian Contract Act, 1872. If You are under 18 years of age, then please do not use or access the Service(s) at any time or in any manner. If We learn that a person under 18 years of age has used or accessed the Platform or Service or any personally identifiable information has been collected on the Platform from persons under 18 years of age, then We will take the appropriate steps to delete this information. If You are a parent or guardian and discover that Your child under 18 years of age has obtained an account on or otherwise accessed the Service, then You may alert Us at{" "}
              <a href="mailto:swasth@affordplan.com">swasth@affordplan.com</a> or call at{" "}
              <a href="tel:+919250050501">+91 9250050501</a> and request that We delete that child's personally identifiable information from our systems.
            </p>

            <h2>16. INDEMNITY</h2>
            <p>
              By accepting these Terms and using the Affordplan Platform, the User agrees that the User shall defend, indemnify and hold the Company, its directors, shareholders, officers and other representatives harmless from and against any and all claims, costs, damages, losses, liabilities and expenses (including attorneys' fees and costs) arising out of or in connection with:
            </p>
            <ul>
              <li>User's access to the Affordplan Platform;</li>
              <li>User's use of the services/features of the Affordplan Platform;</li>
              <li>User's violation or breach of these Terms or any applicable law or regulation;</li>
              <li>User's violation of any rights of any third party including intellectual property or other right of any person or entity; or</li>
              <li>Any third-party claims based upon the content of any communications transmitted by the User.</li>
            </ul>

            <h2>17. TERMINATION</h2>
            <p>
              These Terms will continue to apply until terminated by either the Company or the User as set forth below.
            </p>
            <p>
              <strong>Termination by the User</strong> - If the User elects not to be bound by these Terms, the User may terminate the relationship with the Company by unsubscribing to the Affordplan Platform subject to the terms provided for in the User Agreement or the Merchant Agreement as the case may be.
            </p>
            <p>
              <strong>Termination by the Company</strong> - The Company may at its discretion and at any time with or without notice, terminate or suspend the Terms, with or without cause if:
            </p>
            <ul>
              <li>User is in breach of any of the provisions of the Terms, the Privacy Policy or any other terms, conditions, or policies that may be applicable to the User;</li>
              <li>The Company is mandated to do so in accordance with the law; or</li>
              <li>The Company has elected to discontinue, with or without reason, access to the Affordplan Platform (or any part thereof) either in general or specifically to the User.</li>
            </ul>
            <p>
              The Company shall not be liable to the User or any third party for any such termination.
            </p>

            <h2>18. CONSEQUENCES OF TERMINATION</h2>
            <p>
              Once the User Account has been terminated, any and all content will be irretrievably deleted by the Company, except to the extent that the Company is obliged to maintain or permitted to retain it in accordance with the applicable laws.
            </p>
            <p>
              The limited licences or assignment granted for use to the User in accordance with these Terms shall stand terminated, effective immediately.
            </p>
            <p>
              The Company, in its sole discretion, may initiate appropriate legal proceedings against the User, if necessary, in the event the termination is on account of the User's breach of these Terms.
            </p>
            <p>
              Termination shall not affect User's liability or obligations arising prior to such termination and for the sake of avoidance of any doubt, it is hereby clarified that deletion, uninstallation of the Affordplan Platform and/or discontinuation of the Company's Services, shall not discharge the User from the responsibility, obligation and liability to repay outstanding amount(s), if any, in accordance with these Terms.
            </p>

            <h2>19. FORCE MAJEURE</h2>
            <p>
              Notwithstanding the limitations or disclaimers outlined in these Terms, the Company shall not be held responsible for any delay or failure in performance, whether directly or indirectly caused, which is beyond their control. This includes but is not limited to, incidents such as internet errors, electrical power failures, damage to computer or telecommunication equipment, labour strikes, disputes, civil unrest, natural disasters, governmental actions, epidemics or pandemics, court orders from domestic or foreign jurisdictions, and negligent actions carried out by third parties.
            </p>

            <h2>20. GOVERNING LAW AND JURISDICTION</h2>
            <p>
              These Terms shall be governed and construed under the laws of India and the courts of Gurugram, Haryana shall have exclusive jurisdiction.
            </p>

            <h2>21. DISPUTE RESOLUTION</h2>
            <p>
              The competent courts situated in Gurugram, Haryana shall possess exclusive jurisdiction to adjudicate upon all disputes arising from or associated with the Services offered by the Company.
            </p>
            <p>
              The arbitration award will be final and binding on the Parties, and each Party will bear its costs of arbitration and equally share the fees of the arbitrator unless the arbitral tribunal decides otherwise.
            </p>

            <h2>22. AMENDMENT AND MODIFICATION</h2>
            <p>
              The Affordplan Platform reserves the right to modify these Terms at any time with or without any further notice(s) by uploading the revised Terms on the Affordplan Platform and it is Your duty to keep itself aware of the revisions to the Terms of the Affordplan Platform.
            </p>

            <h2>23. OTHER ADDITIONAL TERMS</h2>
            <p>
              <strong>Special Offers and/or Coupons and/or Cashbacks:</strong> The Company keeps on updating special offers, coupons and cashback points for its End Users on the Affordplan Platform. The Customers can choose to avail the same according to the Terms specified therein.
            </p>
            <p>
              In the event any service delivery is delayed or is cancelled by the Merchant on account of a mistake by the End User (e.g. providing the wrong or other incorrect/misleading information), any additional costs incurred by the Company for this event shall be borne by the End User.
            </p>

            <h2>24. MISCELLANEOUS</h2>
            <p>
              To the extent that anything in or associated with the Affordplan Platform is in conflict or inconsistent with these Terms, these Terms shall take precedence and prevail. The Company's failure to enforce any provision of these Terms shall not be deemed a waiver of such provision nor of the right to enforce such provision. The Company's rights under these Terms shall survive any discontinuance of the access or use of the Affordplan Platform.
            </p>
            <p>
              If any provision of these Terms is held to be invalid or unenforceable, such provision shall be struck and the remaining provisions shall be enforced to the fullest extent under law.
            </p>
            <p>
              Any notices to the User from the Company regarding the Affordplan Platform or these Terms shall be posted on the Affordplan Platform or sent by email or regular mail.
            </p>
            <p>
              The Company reserves the right to assign any rights as it deems fit to any third party whatsoever.
            </p>

            <h2>25. GRIEVANCE REDRESSAL OFFICER</h2>
            <p>
              The Company is committed to addressing User grievances promptly. For internal resolution, Users can contact customer support. If dissatisfied, escalate the matter to the Grievance Officer. External authorities, such as the Data Protection Board of India, may be approached if the resolution is not satisfactory. The Company pledges fair and timely redressal, and no retaliatory action will be taken against Users for raising grievances in good faith. The Company reserves the right to modify the grievance redressal mechanism, with any changes communicated on the Affordplan Platform. For assistance, contact customer care at{" "}
              <a href="tel:+919250050501">+91-92500 50501</a>.
            </p>

            <h2>GLOSSARY</h2>
            <p>
              <strong>"Customer(s)"</strong> means persons obtaining Healthcare Services from the Merchants and includes a walk-in customer.
            </p>
            <p>
              <strong>"Device"</strong>, for the purposes of these Terms, means a device, usually electronic, that processes data according to a set of instructions, which may include workstations, personal computers, laptops, netbooks, personal digital assistants, tablets, smartphones, etc.
            </p>
            <p>
              <strong>"End User"</strong> shall mean the Customers who have successfully registered with the Company and have entered into the User Agreement.
            </p>
            <p>
              <strong>"Financial Counsellor"</strong> shall mean an employee or representative of the Company who will be available at the Merchants's location and will be responsible for undertaking the registration process of the Users on the Affordplan Platform and providing end-to-end support to the Users.
            </p>
            <p>
              <strong>"Healthcare Services"</strong> may include services such as emergency services, primary care providers, inpatient services, outpatient services, specialized care, maternity and childcare, delivery or purchase of medicines from the pharmacy, collection of samples at home, etc. offered by the Merchants and as displayed on the link provided on the Affordplan Platform and as updated from time to time.
            </p>
            <p>
              <strong>"Loyalty Program"</strong> shall mean the program offered or provided by the Company on the Affordplan Platform to the Users to obtain Swasth Points;
            </p>
            <p>
              <strong>"Merchants"</strong> shall include a group of hospitals, diagnostics, laboratories, research labs, pharmacies, etc. owned or leased and operated under one brand name of a hospital registered duly under the applicable laws and empanelled with the Company on the AffordPlan Platform.
            </p>
            <p>
              <strong>"Merchant Agreement"</strong> shall mean the agreement entered into by the Merchant and the Company, wherein the Merchant will provide Healthcare Services and the Company will provide its Services to the extent of payment facilitator.
            </p>
            <p>
              <strong>"User(s)"</strong> for the purpose of these Terms shall include the Service Providers, Permitted User or the End User or any third person visiting the Affordplan Platform or availing the Services of the Company, wherever the context so requires, the term "You" or "Your" shall mean any natural or legal person.
            </p>
            <p>
              <strong>"Payment Options"</strong> shall mean the payment made through the Affordplan App by scanning the QR Code placed with the Merchants, or by using vouchers issued by the Company to the End Users according to its policies, or through payment links/options that may be made available on the Affordplan App by the Company, through availing option like pay later, loan facilitation, or any other mode of payment as the Company may allow, at its sole discretion, through the Affordplan App;
            </p>
            <p>
              <strong>"Permitted User"</strong> shall be the Merchant who have agreed to engage the Company for its Services and have entered into the Merchant Agreement.
            </p>
            <p>
              <strong>"Services"</strong> shall mean the facilitation services or limited assistance services pertaining to Healthcare Services being provided to the Permitted User and the End Users or any other services (including but not limited to marketing of various products on the Affordplan App, financing options and loan products, insurance, and such other services as the Company may introduce, from time to time) offered by the Company to the Permitted User and/or the End Users in terms of the Merchant Agreement and/ or the User Agreement.
            </p>
            <p>
              <strong>"Service Providers"</strong> shall mean the third-party service provider engaged with the Company whose products are displayed and offered on the Affordplan App;
            </p>
            <p>
              <strong>"Swasth Points"</strong> means a Loyalty Program benefit earned by End Users for payments made through the Affordplan App with a validity period as may be approved by the Merchant and the Company. These points may be redeemed by the End Users on future payments made through the Affordplan App or by using the Payment Options for availing Healthcare Services with the Merchant.
            </p>
            <p>
              <strong>"Transaction"</strong> means the successful payment using the Affordplan Platform, towards Healthcare Services obtained by the End User from the Merchant.
            </p>
            <p>
              <strong>"Upgrades"</strong> shall mean and include new versions of, and updates to, the Affordplan Platform whether to fix an error, bug or other issue in the Affordplan Platform or enhance the functionality of the Affordplan Platform.
            </p>
            <p>
              <strong>"User Agreement"</strong> shall mean the agreement entered into between the Customer and the Company at the time of registration of the User Account.
            </p>
          </div>
        </div>
      </div>
    </main>
  );
}